let ordenExposicion = { tabla: 'nombre', dir: 'asc' };
let ordenExposicionAcum = { campo: 'nombre', dir: 'asc' };
function renderExposicion(estado, contenedor, guardarYRefrescar) {
  const datos = listarExposicion(estado).map(e=>datosExposicion(estado,e));
  const ids = [...new Set(datos.map(d=>d.luchadorId))];
  const ordenados = ordenarExposicion(datos, ordenExposicion);
  const acumulados = ids.map(id=>{const r=resumenExposicion(estado,id); const w=obtenerLuchadorParaHistorial(estado,id); return {...r,id,nombre:w.nombre,show:normalizarShows(w.shows??w.show).join(', '),participacion:clasificarParticipacion(r.totalCombates),tendencia:clasificarTendencia(r)};}).sort((a,b)=>compararValores(valorOrdenAcum(a,ordenExposicionAcum.campo),valorOrdenAcum(b,ordenExposicionAcum.campo),ordenExposicionAcum.dir));
  const th=(campo,label)=>`<th data-exp-sort="${campo}">${label}${ordenExposicion.tabla===campo?(ordenExposicion.dir==='asc'?' ▲':' ▼'):''}</th>`;
  const tha=(campo,label)=>`<th data-exp-acum-sort="${campo}">${label}${ordenExposicionAcum.campo===campo?(ordenExposicionAcum.dir==='asc'?' ▲':' ▼'):''}</th>`;
  contenedor.innerHTML = `<h2>👀 Exposición</h2><p class="texto-tenue">Lista manual. Las estadísticas siguen teniendo una única fuente: Temporadas. Desde acá también podés editar V/D de cada temporada.</p>
    <div class="panel"><div class="panel-header"><h3>Agregar luchador</h3></div><div class="form-grid"><label>Luchador<select id="exp-luchador"><option value="">Elegir...</option>${estado.roster.slice().sort((a,b)=>a.nombre.localeCompare(b.nombre)).map(w=>`<option value="${w.id}">${esc(w.nombre)}</option>`).join('')}</select></label><label>Temporada<select id="exp-temp"><option value="">Elegir...</option>${estado.temporadas.map(t=>`<option value="${t.id}">${esc(t.id)}</option>`).join('')}</select></label></div><button class="accion" id="exp-agregar">➕ Agregar</button></div>
    <div class="panel"><div class="panel-header"><h3>Seguimiento por temporada</h3><button class="accion" id="exp-guardar-todo">💾 Guardar todo</button></div><div class="tabla-scroll"><table><thead><tr>${th('nombre','Luchador')}${th('show','Show actual')}${th('temporada','Temporada')}${th('victorias','V')}${th('derrotas','D')}${th('totalCombates','Total combates')}${th('balance','Balance')}${th('participacion','Participación')}${th('tendencia','Racha / tendencia')}${th('puntos','Puntos')}<th>Acciones</th></tr></thead><tbody>${ordenados.map(d=>`<tr><td>${esc(d.nombre)}</td><td>${chipsShows(d.show)}</td><td>${esc(d.temporada)}</td><td><input type="number" min="0" data-exp-v="${d.indice}" value="${d.calc?.deltas.victorias??0}"></td><td><input type="number" min="0" data-exp-d="${d.indice}" value="${d.calc?.deltas.derrotas??0}"></td><td>${d.calc?d.calc.deltas.victorias+d.calc.deltas.derrotas:'—'}</td><td>${d.balance??'—'}</td><td>${clasificarParticipacion(d.calc?(d.calc.deltas.victorias+d.calc.deltas.derrotas):0)}</td><td>${clasificarTendencia({entradas:[d],victorias:d.calc?.deltas.victorias||0,derrotas:d.calc?.deltas.derrotas||0})}</td><td>${d.calc?.puntosTemporada??'—'}</td><td><button class="accion secundaria" data-exp-del="${d.indice}">🗑️</button></td></tr>`).join('')}</tbody></table></div></div>
    <div class="panel"><h3>Acumulado histórico de Exposición</h3><div class="tabla-scroll"><table><thead><tr>${tha('nombre','Luchador')}${tha('show','Show actual')}${tha('temporadas','Temporadas seguidas')}${tha('victorias','Victorias')}${tha('derrotas','Derrotas')}${tha('totalCombates','Total combates')}${tha('balance','Balance V-D')}${tha('participacion','Participación')}${tha('tendencia','Racha / tendencia')}</tr></thead><tbody>${acumulados.map(r=>`<tr><td>${esc(r.nombre)}</td><td>${chipsShows(r.show)}</td><td>${r.entradas.map(x=>esc(x.temporada)).join(', ')}</td><td>${r.victorias}</td><td>${r.derrotas}</td><td>${r.totalCombates}</td><td>${r.balance}</td><td>${r.participacion}</td><td>${r.tendencia}</td></tr>`).join('')}</tbody></table></div><p class="texto-tenue">La racha exacta combate por combate todavía no existe en los datos. El indicador muestra la tendencia disponible.</p></div>`;
  contenedor.querySelector('#exp-agregar').onclick=()=>{try{agregarExposicion(contenedor.estado||estado,contenedor.querySelector('#exp-luchador').value,contenedor.querySelector('#exp-temp').value);guardarYRefrescar();}catch(e){alert(e.message);}};
  contenedor.querySelector('#exp-guardar-todo').onclick=()=>{try{ordenados.forEach(d=>{const t=obtenerTemporada(estado,d.temporadaId);if(!t||t.cerrada)throw new Error(`La temporada ${d.temporadaId} está cerrada.`);const v=Number(contenedor.querySelector(`[data-exp-v="${d.indice}"]`).value),der=Number(contenedor.querySelector(`[data-exp-d="${d.indice}"]`).value);if(!Number.isInteger(v)||v<0||!Number.isInteger(der)||der<0)throw new Error('Victorias y derrotas deben ser enteros no negativos.');const prevR=t.anterior?obtenerRegistro(obtenerTemporada(estado,t.anterior),d.luchadorId):null;actualizarAcumulados(estado,t.id,d.luchadorId,{victoriasAcum:(prevR?.victoriasAcum??0)+v,derrotasAcum:(prevR?.derrotasAcum??0)+der});});guardarYRefrescar();}catch(e){alert(e.message);}};
  contenedor.querySelectorAll('[data-exp-del]').forEach(b=>b.onclick=()=>{if(confirm('¿Quitar este registro de Exposición? No se borrarán las estadísticas de la temporada.')){eliminarExposicion(estado,Number(b.dataset.expDel));guardarYRefrescar();}});
  contenedor.querySelectorAll('[data-exp-sort]').forEach(h=>h.onclick=()=>{const c=h.dataset.expSort;ordenExposicion.dir=ordenExposicion.tabla===c?(ordenExposicion.dir==='asc'?'desc':'asc'):'asc';ordenExposicion.tabla=c;renderExposicion(estado,contenedor,guardarYRefrescar);});
  contenedor.querySelectorAll('[data-exp-acum-sort]').forEach(h=>h.onclick=()=>{const c=h.dataset.expAcumSort;ordenExposicionAcum.dir=ordenExposicionAcum.campo===c?(ordenExposicionAcum.dir==='asc'?'desc':'asc'):'asc';ordenExposicionAcum.campo=c;renderExposicion(estado,contenedor,guardarYRefrescar);});
}
function ordenarExposicion(lista,o){return lista.slice().sort((a,b)=>compararValores(valorOrdenExposicion(a,o.tabla),valorOrdenExposicion(b,o.tabla),o.dir));}
function valorOrdenExposicion(d,c){if(c==='nombre'||c==='show'||c==='temporada')return c==='show'?normalizarShows(d.show).join(', '):d[c];if(c==='victorias')return d.calc?.deltas.victorias??-Infinity;if(c==='derrotas')return d.calc?.deltas.derrotas??-Infinity;if(c==='totalCombates')return d.calc?(d.calc.deltas.victorias+d.calc.deltas.derrotas):-Infinity;if(c==='balance')return d.balance??-Infinity;if(c==='participacion')return {Poca:1,Media:2,Mucha:3}[clasificarParticipacion(d.calc?(d.calc.deltas.victorias+d.calc.deltas.derrotas):0)];if(c==='tendencia')return clasificarTendencia({entradas:[d],victorias:d.calc?.deltas.victorias||0,derrotas:d.calc?.deltas.derrotas||0});if(c==='puntos')return d.calc?.puntosTemporada??-Infinity;return ''}
function valorOrdenAcum(r,c){if(c==='show')return r.show;if(c==='temporadas')return r.entradas.map(x=>x.temporada).join(', ');return r[c];}
function compararValores(a,b,dir='asc'){let c=typeof a==='string'?String(a??'').localeCompare(String(b??''),'es',{sensitivity:'base'}):(Number(a??-Infinity)-Number(b??-Infinity));return dir==='asc'?c:-c;}
function clasificarParticipacion(total){if(total<=10)return 'Poca';if(total<=30)return 'Media';return 'Mucha';}
function clasificarTendencia(r){if((r.victorias||0)>(r.derrotas||0))return '🟢 Buena';if((r.victorias||0)<(r.derrotas||0))return '🔴 Mala';return '🟡 Pareja';}
